name: mobile_app_translate
description: A versatile translation app with text, voice, camera OCR, and object detection.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # State Management
  get: ^4.7.2

  # ML Kit
  google_mlkit_translation: ^0.13.1
  google_mlkit_text_recognition: ^0.15.1
  google_mlkit_object_detection: ^0.15.1

  # Speech & TTS
  speech_to_text: ^7.3.0
  flutter_tts: ^4.2.3

  # Camera & Image
  camera: ^0.11.1
  image_picker: ^1.2.1

  # Storage
  shared_preferences: ^2.5.0

  # UI Components
  dropdown_button2: ^3.0.0-beta
  avatar_glow: ^3.0.1
  google_fonts: ^6.2.1

  # Permissions
  permission_handler: ^11.4.0

  # Utilities
  path_provider: ^2.1.5
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/ml/
